/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.7
 * Generated at: 2025-06-30 19:05:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("<head>\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("<head>\r\n");
      out.write("   <meta charset=\"UTF-8\">\r\n");
      out.write("   <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("   <title>SABI - Inicio de Sesión</title>\r\n");
      out.write("   <link rel=\"stylesheet\" type=\"text/css\" href=\"estilos/login.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  \r\n");
      out.write("    ");
System.out.println("iniciamos sabi");
      out.write("\r\n");
      out.write("   <!-- Sección de Login -->\r\n");
      out.write("   <section class=\"login-section\">\r\n");
      out.write("       <div class=\"login-container\">\r\n");
      out.write("           <div class=\"login-card\">\r\n");
      out.write("               <h1>Inicio de Sesión</h1>\r\n");
      out.write("               <div class=\"divider\">\r\n");
      out.write("                   <span>O regístrate</span>\r\n");
      out.write("               </div>\r\n");
      out.write("               <form class=\"login-form\" method=\"POST\" action=\"ValidarUsuarioController\">\r\n");
      out.write("                   <div class=\"form-group\">\r\n");
      out.write("                       <label>Correo Electrónico</label>\r\n");
      out.write("                       <input name=\"emaUsuario\" type=\"email\" placeholder=\"correo@ejemplo.com\">\r\n");
      out.write("                   </div>\r\n");
      out.write("                   <div class=\"form-group\">\r\n");
      out.write("                       <label>Contraseña</label>\r\n");
      out.write("                       <input name=\"passUsuario\" type=\"password\" placeholder=\"Tu contraseña\">\r\n");
      out.write("                   </div>\r\n");
      out.write("                   <button name=\"accion\" value=\"Ingresar\" type=\"submit\" class=\"login-btn\">Iniciar Sesión</button>\r\n");
      out.write("                   <a href=\"registro.jsp\" class=\"register-link\">No tienes cuenta Regístrate aquí</a>\r\n");
      out.write("               </form>\r\n");
      out.write("           </div>\r\n");
      out.write("           <div class=\"logo-section\">\r\n");
      out.write("               <div class=\"logo\">\r\n");
      out.write("                   <img src=\"recursos/logoF.png\" alt=\"SABI Logo\" class=\"logo-img\">\r\n");
      out.write("               </div>\r\n");
      out.write("           </div>\r\n");
      out.write("       </div>\r\n");
      out.write("   </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   <!-- Sección Principal -->\r\n");
      out.write("   <section class=\"main-section\">\r\n");
      out.write("       <header class=\"main-header\">\r\n");
      out.write("       </header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("       <div class=\"content-container\">\r\n");
      out.write("           <div class=\"welcome-section\">\r\n");
      out.write("               <h2>QUE ES SABI</h2>\r\n");
      out.write("               <p>En SABI, nuestro método de entrenador a la demanda. Un entrenador que evoluciona activamente a través de programas de entrenamiento gratuitos.</p>\r\n");
      out.write("           </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("           <div class=\"features-grid\">\r\n");
      out.write("               <div class=\"feature-card\">\r\n");
      out.write("                   <h3>¡Descubre los Entrenamientos de SABI!</h3>\r\n");
      out.write("                   <ul>\r\n");
      out.write("                       <li><strong>Entrenamientos de SABI:</strong></li>\r\n");
      out.write("                       <li>En SABI enseñamos diversas formas de mejorar tu bienestar físico.</li>\r\n");
      out.write("                       <li><strong>Rutinas Personalizadas:</strong> Nuestros Entrenadores que crean programas específicos para cada usuario basándose en sus necesidades y objetivos.</li>\r\n");
      out.write("                       <li><strong>Rutinas Preestablecidas:</strong> Explora y sigue nuestras rutinas de ejercicios diseñadas por expertos.</li>\r\n");
      out.write("                       <li><strong>Crea tus Propias Rutinas:</strong> Utiliza nuestras herramientas para diseñar y personalizar tus propios entrenamientos.</li>\r\n");
      out.write("                       <li><strong>Con SABI,</strong> optimizamos tu creación y gestión de programas de entrenamientos asegurándonos todo por tu mejor experiencia, todo en un solo lugar.</li>\r\n");
      out.write("                   </ul>\r\n");
      out.write("               </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("               <div class=\"feature-card\">\r\n");
      out.write("                   <h3>Transformaciones con SABI</h3>\r\n");
      out.write("                   <p>Nuestros usuarios han experimentado cambios increíbles en sus vidas gracias a nuestros programas de entrenamiento personalizado. Desde mejoras en su bienestar físico hasta alcanzar sus objetivos de fitness, aquí tienes algunos testimonios de quienes ya han transformado sus vidas con SABI.</p>\r\n");
      out.write("                   <p>Con SABI, cada usuario puede encontrar el programa perfecto que se adapte a sus necesidades específicas, ya sea para principiantes o atletas avanzados. Nuestro enfoque personalizado garantiza resultados efectivos y duraderos.</p>\r\n");
      out.write("               </div>\r\n");
      out.write("           </div>\r\n");
      out.write("       </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("       <footer class=\"main-footer\">\r\n");
      out.write("           <div class=\"footer-content\">\r\n");
      out.write("               <div class=\"footer-section\">\r\n");
      out.write("                   <h4>Políticas de privacidad</h4>\r\n");
      out.write("                   <ul>\r\n");
      out.write("                       <li><a href=\"#\">Política de datos</a></li>\r\n");
      out.write("                       <li><a href=\"#\">Aviso de privacidad</a></li>\r\n");
      out.write("                   </ul>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"footer-section\">\r\n");
      out.write("                   <h4>Términos de servicio</h4>\r\n");
      out.write("                   <ul>\r\n");
      out.write("                       <li><a href=\"#\">Términos y condiciones</a></li>\r\n");
      out.write("                       <li><a href=\"#\">Reglas de uso</a></li>\r\n");
      out.write("                   </ul>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"footer-section\">\r\n");
      out.write("                   <h4>Información de contacto</h4>\r\n");
      out.write("                   <ul>\r\n");
      out.write("                       <li>1234567484</li>\r\n");
      out.write("                       <li>2534647484</li>\r\n");
      out.write("                       <li>SABI@gmail.com</li>\r\n");
      out.write("                   </ul>\r\n");
      out.write("               </div>\r\n");
      out.write("           </div>\r\n");
      out.write("           <div class=\"footer-bottom\">\r\n");
      out.write("               <p>&copy; 2024 SABI. Todos los derechos reservados.</p>\r\n");
      out.write("               <div class=\"social-icons\">\r\n");
      out.write("                   <a href=\"#\">📧</a>\r\n");
      out.write("                   <a href=\"#\">📱</a>\r\n");
      out.write("                   <a href=\"#\">🐦</a>\r\n");
      out.write("               </div>\r\n");
      out.write("           </div>\r\n");
      out.write("       </footer>\r\n");
      out.write("   </section>\r\n");
      out.write("</body>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
