/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.7
 * Generated at: 2025-06-30 04:03:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.vistas.Entrenador;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import Modelo.Maximos;
import Modelo.Ejercicio_Rutina;

public final class formRutina_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("Modelo.Maximos");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("Modelo.Ejercicio_Rutina");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 String contextPath = request.getContextPath();
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css\" rel=\"stylesheet\"\r\n");
      out.write("              integrity=\"sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT\"\r\n");
      out.write("              crossorigin=\"anonymous\">\r\n");
      out.write("        <link rel=\"stylesheet\"\r\n");
      out.write("              href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css\">\r\n");
      out.write("        <title>Crea tu rutina</title>\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"");
      out.print( contextPath);
      out.write("/estilos/formRutina.css\">\r\n");
      out.write("    </head>\r\n");
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("        ");
Maximos max = (Maximos) session.getAttribute("max");
        if (max == null) {
      out.write("\r\n");
      out.write("        <div class=\"col-md-5 m-auto\">\r\n");
      out.write("            <h1>Estructura tu rutina</h1>\r\n");
      out.write("            <form id=\"estructuraRutina\" method=\"GET\" action=\"");
      out.print( contextPath);
      out.write("/Ejercicio_RutinaController\">\r\n");
      out.write("                <input type=\"hidden\" name=\"accion\" value=\"Create\">\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"numSemanas\">Cuantas semanas deseas en tu rutina?</label>\r\n");
      out.write("                    <input name=\"numSemanas\" type=\"number\" class=\"form-control\" id=\"numSemanas\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"numDias\">Cuantos dias quieres por semana?\r\n");
      out.write("                        (Posteriormente podras borrar los dias o ejercicios sobrantes)</label>\r\n");
      out.write("                    <input name=\"numDias\" type=\"number\" class=\"form-control\" id=\"numDias\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"numEjercicios\">Cuantos ejercicios quieres en cada dia?</label>\r\n");
      out.write("                    <input name=\"numEjercicios\" type=\"number\" class=\"form-control\" id=\"numEjercicios\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card-title mb-0 text-center\">\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-primary me-2 mt-2\">\r\n");
      out.write("                        Generar tabla\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("        ");
} else {
      out.write("\r\n");
      out.write("        <div id=\"contenedorTabla\" class=\"col-md-8 mx-auto text-center\">\r\n");
      out.write("            <h1 class=\"mb-4 mt-5\">Crea tu rutina</h1>\r\n");
      out.write("            <button class=\"mb-5 btn btn-success mx-auto\" type=\"button\" data-bs-toggle=\"modal\" data-bs-target=\"#guardarRutina\">Guardar Rutina</button>\r\n");
      out.write("            ");
for (int i = 1; i <= max.getSemanas(); i++) {
      out.write("\r\n");
      out.write("            <div class=\"semana text-center mb-5\">\r\n");
      out.write("                <h2 class=\"mb-3\">Semana ");
      out.print(i);
      out.write("</h2>\r\n");
      out.write("                <table class=\"table table-md table-bordered\">\r\n");
      out.write("                    <thead>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            ");
for (int j = 1; j <= max.getDias(); j++) {
      out.write("\r\n");
      out.write("                            <th class=\"mx-2\">Dia ");
      out.print(j);
      out.write("</th>\r\n");
      out.write("                                ");
}
      out.write("\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </thead>\r\n");
      out.write("                    <tbody>\r\n");
      out.write("                        ");
for (int k = 1; k <= max.getEjercicios(); k++) {
      out.write("\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                ");
for (int j = 1; j <= max.getDias(); j++) {
      out.write("\r\n");
      out.write("                                    ");
List<Modelo.Ejercicio_Rutina> ejercicios = (List<Modelo.Ejercicio_Rutina>) session.getAttribute("ejerciciosRutina");
                                        boolean encontrado = false;

                                        if (ejercicios != null) {
                                            for (Modelo.Ejercicio_Rutina ejer : ejercicios) {
                                                if (ejer.getSemana() == i && ejer.getDia() == j && ejer.getOrdenEjercicio() == k) {
                                                    encontrado = true;
                                        
      out.write("\r\n");
      out.write("                                        <td class=\"celda position-relative p-0\">\r\n");
      out.write("                                            <div style=\"display: flex; justify-content: space-between; align-items: center; width: 100%; padding: 8px 12px;\">\r\n");
      out.write("                                                <a class=\"editar\" href=\"");
      out.print( contextPath);
      out.write("/EjercicioController?accion=TraerEjercicio&semana=");
      out.print(i);
      out.write("&dia=");
      out.print(j);
      out.write("&ordenEjercicio=");
      out.print(k);
      out.write("&fkIdEjercicio=");
      out.print(ejer.getFkIdEjercicio());
      out.write("\" \r\n");
      out.write("                                                    style=\"flex-grow: 1; text-decoration: none; color: ");
      out.print(ejer.getEstilo());
      out.write(";\">\r\n");
      out.write("                                                    ");
      out.print(ejer.getNomEjercicio());
      out.write("\r\n");
      out.write("                                                </a>\r\n");
      out.write("                                                <a class=\"eliminar\" href=\"");
      out.print( contextPath);
      out.write("/Ejercicio_RutinaController?accion=Delete&semana=");
      out.print(i);
      out.write("&dia=");
      out.print(j);
      out.write("&ordenEjercicio=");
      out.print(k);
      out.write("&fkIdEjercicio=");
      out.print(ejer.getFkIdEjercicio());
      out.write("\">\r\n");
      out.write("                                                    <i class=\"bi bi-trash3-fill\"></i>\r\n");
      out.write("                                                </a>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </td>\r\n");
      out.write("                                        ");

                                                    break; // ya encontramos el ejercicio, salimos del for
                                                }
                                            }
                                        }

                                        if (!encontrado) {
                                        
      out.write("\r\n");
      out.write("                                            <td class=\"td-vacio\"></td> <!-- Aquí generas la celda vacía -->\r\n");
      out.write("                                        ");

                                        }
                                }
      out.write("\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        ");
}
      out.write("    \r\n");
      out.write("                    </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("            </div>\r\n");
      out.write("            ");
}
      out.write("\r\n");
      out.write("            <!-- Modal -->\r\n");
      out.write("            <div class=\"modal fade\" id=\"guardarRutina\" aria-labelledby=\"titulos\" aria-hidden=\"true\">\r\n");
      out.write("                <div class=\"modal-dialog modal-dialog-centered\">\r\n");
      out.write("                    <div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"modal-header\">\r\n");
      out.write("                            <h5 class=\"modal-title\" id=\"titulos\">Guarda los datos de tu rutina</h5>\r\n");
      out.write("                            <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Cerrar\"></button>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"modal-body\">\r\n");
      out.write("                            <form id=\"edicionUsuario\" action=\"");
      out.print(contextPath);
      out.write("/RutinaController\">\r\n");
      out.write("                                <input type=\"hidden\" name=\"semanasRutina\" value=\"");
      out.print(max.getSemanas());
      out.write("\">\r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                    <label for=\"NomRutina\">Asignale un nombre a tu rutina</label>\r\n");
      out.write("                                    <input name=\"nomRutina\" type=\"text\" class=\"form-control\" id=\"NomRutina\" required>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                    <label for=\"DescRutina\">Describe esta rutina</label>\r\n");
      out.write("                                    <input name=\"descRutina\" type=\"text\" class=\"form-control\" id=\"DescRutina\" required>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                    <label for=\"nomUsuario\">De que nivel es tu rutina?</label>\r\n");
      out.write("                                    <select name=\"nivelRutina\" class=\"form-control\" id=\"rolUsuario\" required>\r\n");
      out.write("                                        <option value=\"\"></option>\r\n");
      out.write("                                        <option value=\"basico\">Basica</option>\r\n");
      out.write("                                        <option value=\"intermedio\">Intermedia</option>\r\n");
      out.write("                                        <option value=\"avanzado\">Avanzada</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"modal-footer\">\r\n");
      out.write("                            <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Cancelar</button>\r\n");
      out.write("                            <button type=\"submit\" name=\"accion\" value=\"Create\" class=\"btn btn-success\" form=\"edicionUsuario\">Guardar cambios</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        ");
}
      out.write("\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
