/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.7
 * Generated at: 2025-06-30 13:30:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.vistas.Entrenador;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class rutinas_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/plantillas/dashEntrenador.jsp", Long.valueOf(1751289078795L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
String contextPath = request.getContextPath();
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"es\">\n");
      out.write("\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <title>Tus Rutinas</title>\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( contextPath);
      out.write("/estilos/indexEntre.css\">\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css\" rel=\"stylesheet\"\n");
      out.write("              integrity=\"sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT\"\n");
      out.write("              crossorigin=\"anonymous\">\n");
      out.write("        <link rel=\"stylesheet\"\n");
      out.write("              href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css\">\n");
      out.write("        <style>\n");
      out.write("            .pattern-bg {\n");
      out.write("                background-image: url('../recursos/fondoSabiNuevo.png');\n");
      out.write("            }\n");
      out.write("        </style>\n");
      out.write("    </head>\n");
      out.write("\n");
      out.write("    <body class=\"pattern-bg\">\n");
      out.write("        <!-- Header -->\n");
      out.write("        ");

    Modelo.Usuario cliente = (Modelo.Usuario) session.getAttribute("logger");

      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print( contextPath);
      out.write("/estilos/barranavegacion.css\">\n");
      out.write("<header class=\"superior\">\n");
      out.write("    <div class=\"izquierda\">\n");
      out.write("        <img src=\"");
      out.print( contextPath);
      out.write("/recursos/logoLargo.png\" alt=\"Logo\" class=\"logo\">\n");
      out.write("    </div>\n");
      out.write("    <nav>\n");
      out.write("        <a href=\"");
      out.print( contextPath);
      out.write("/vistas/Entrenador/rutinas.jsp\">\n");
      out.write("            <span>Rutinas</span>\n");
      out.write("        </a>\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath());
      out.write("/SuscripcionController?menu=Suscripciones&accion=listar\">\n");
      out.write("            <span>Clientes</span>\n");
      out.write("        </a>\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath());
      out.write("/SuscripcionController?menu=Suscripciones&accion=listar\">\n");
      out.write("            <span>Suscripciones</span>\n");
      out.write("        </a>\n");
      out.write("    </nav>\n");
      out.write("    <div class=\"derecha\">\n");
      out.write("        <img src=\"");
      out.print( contextPath);
      out.write("/recursos/cliente.jpg\" alt=\"user\" class=\"user\">\n");
      out.write("        <span>");
      out.print( cliente.getNomUsuario() );
      out.write(' ');
      out.print( cliente.getApeUsuario() );
      out.write(' ');
      out.write('|');
      out.write(' ');
      out.print( cliente.getRolUsuario() );
      out.write("</span>\n");
      out.write("    </div>\n");
      out.write("</header>");
      out.write("\n");
      out.write("        <div class=\"col-md-3 mx-auto text-center\"> \n");
      out.write("            <h1>Tus rutinas</h1>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"col-md-8 mx-auto row\">\n");
      out.write("            <div class=\"col-md-12 row\">\n");
      out.write("                <!-- filtros -->\n");
      out.write("                <div class=\"col-md-4 me-auto\">\n");
      out.write("                    fitlros\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-md-4 ms-auto\">\n");
      out.write("                    <button class=\"btn btn-success ms-auto\">+ Crear nueva rutina</button>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"rutinas\">\n");
      out.write("                <div class=\"rutina mt-4 row\">\n");
      out.write("                    <div class=\"col-md-3\"></div>\n");
      out.write("                    <div class=\"col-md-6 d-flex\">\n");
      out.write("                        <div class=\"my-auto mx-auto\">\n");
      out.write("                            <h3>Aumento de masa muscular</h3>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-md-3 text-end\">\n");
      out.write("                        Fecha de creacion: 05/11/2024 </br>\n");
      out.write("                        Puntuacion promedio: 4.5 </br>\n");
      out.write("                        Dificultad: Principiante </br>\n");
      out.write("                        Duracion: 4 Semana/s </br>\n");
      out.write("                        Asignada: 5 Clientes </br>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"col-md-7\">\n");
      out.write("                        \n");
      out.write("                        En esta rutina encontraras ejercicios básicos para generar resistencia y ganar masa muscular.\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-md-5\">\n");
      out.write("                        <div class=\"row my-auto mx-auto\">\n");
      out.write("                            <button class=\"editar\">Editar rutina</button>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"row my-auto mx-auto\">\n");
      out.write("                            <button class=\"asignar\" data-bs-toggle=\"modal\" data-bs-target=\"#clientes\">Asignar rutina</button>\n");
      out.write("                        </div>\n");
      out.write("                        \n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
