/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.7
 * Generated at: 2025-07-01 04:46:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.vistas.Cliente;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import Modelo.Usuario;

public final class cliente_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/plantillas/barraNavegacionCliente.jsp", Long.valueOf(1751345174568L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("Modelo.Usuario");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

 String contextPath = request.getContextPath();
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("        <title>Pagina principal del cliente</title>\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"");
      out.print( contextPath);
      out.write("/estilos/indexCliente.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"");
      out.print( contextPath);
      out.write("/estilos/barranavegacion.css\">\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("        ");

    Modelo.Usuario cliente = (Modelo.Usuario) session.getAttribute("logger");

      out.write("\r\n");
      out.write("<header class=\"superior\">\r\n");
      out.write("    <div class=\"izquierda\">\r\n");
      out.write("        <img src=\"");
      out.print( contextPath);
      out.write("/recursos/logoLargo.png\" alt=\"Logo\" class=\"logo\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <nav>\r\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath());
      out.write("/vistas/Cliente/cliente.jsp\">\r\n");
      out.write("            <span>Progreso</span>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"");
      out.print( contextPath);
      out.write("/RutinaController?accion=Read\">\r\n");
      out.write("            <span>Rutinas</span>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath());
      out.write("/EntrenadorController\">\r\n");
      out.write("            <span>Entrenadores</span>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath());
      out.write("/SuscripcionController?menu=Suscripciones&accion=listar&idCliente=");
      out.print( cliente.getIdUsuario() );
      out.write("\">\r\n");
      out.write("            <span>Suscripciones</span>\r\n");
      out.write("        </a>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <div class=\"derecha\">\r\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath());
      out.write("/CerrarSesion\">\r\n");
      out.write("            <span>Cerrar Sesion</span>\r\n");
      out.write("        </a>\r\n");
      out.write("        <img src=\"");
      out.print( contextPath);
      out.write("/recursos/cliente.jpg\" alt=\"user\" class=\"user\">\r\n");
      out.write("        <span>");
      out.print( cliente.getNomUsuario() );
      out.write(' ');
      out.print( cliente.getApeUsuario() );
      out.write(' ');
      out.write('|');
      out.write(' ');
      out.print( cliente.getRolUsuario() );
      out.write("</span>\r\n");
      out.write("    </div>\r\n");
      out.write("</header>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"contenido\">\r\n");
      out.write("            <h1>¡Hola ");
      out.print( cliente.getNomUsuario() );
      out.write(' ');
      out.print( cliente.getApeUsuario() );
      out.write("!</h1>\r\n");
      out.write("            <p>Aún no tienes un diagnóstico inicial.</p>\r\n");
      out.write("            <p>¿Te gustaría realizarlo ahora para que puedas diseñar tu rutina personalizada?</p>\r\n");
      out.write("            <a class=\"boton-accion\" href=\"DiagnosticoController\">Realizar Diagnostico</a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"contenido-estadisticas\">\r\n");
      out.write("            <div class=\"encabezado\">\r\n");
      out.write("                <h1>Estas son tus estadísticas</h1>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"grupo-estadisticas\">\r\n");
      out.write("                <div class=\"estadistica\">\r\n");
      out.write("                    <h2><i class=\"fa-solid fa-weight-scale\"></i> Peso</h2>\r\n");
      out.write("                    <h3>83 kg</h3>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"estadistica\">\r\n");
      out.write("                    <h2><i class=\"bi bi-person-walking\"></i> Niveles de actividad física</h2>\r\n");
      out.write("                    <h3>Sedentario</h3>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"estadistica\">\r\n");
      out.write("                    <h2><i class=\"bi bi-moisture\"></i> Nivel de Hidratación</h2>\r\n");
      out.write("                    <h3>Menos de un litro</h3>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"estadistica\">\r\n");
      out.write("                    <h2><i class=\"bi bi-x-octagon\"></i> Aqui Estadistica</h2>\r\n");
      out.write("                    <h3>descripcion</h3>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"estadistica\">\r\n");
      out.write("                    <h2><i class=\"bi bi-x-octagon\"></i> Aqui Estadistica</h2>\r\n");
      out.write("                    <h3>descripcion</h3>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <a class=\"boton-diagnostico\" href=\"DiagnosticoController\">Actualizar Estadísticas</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
