/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.7
 * Generated at: 2025-07-01 04:46:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.vistas.Cliente;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import Modelo.Rutina;
import java.util.List;

public final class rutinas_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/plantillas/barraNavegacionCliente.jsp", Long.valueOf(1751345174568L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("Modelo.Rutina");
    _jspx_imports_classes.add("java.util.List");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
String contextPath = request.getContextPath();
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("        <title>Tus Rutinas</title>\r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( contextPath);
      out.write("/estilos/rutinas.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( contextPath);
      out.write("/estilos/indexEntre.css\">\r\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css\" rel=\"stylesheet\"\r\n");
      out.write("              integrity=\"sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT\"\r\n");
      out.write("              crossorigin=\"anonymous\">\r\n");
      out.write("        <link rel=\"stylesheet\"\r\n");
      out.write("              href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css\">\r\n");
      out.write("        <style>\r\n");
      out.write("            .pattern-bg {\r\n");
      out.write("                background-image: url('../recursos/fondoSabiNuevo.png');\r\n");
      out.write("            }\r\n");
      out.write("        </style>\r\n");
      out.write("    </head>\r\n");
      out.write("\r\n");
      out.write("    <body class=\"pattern-bg\">\r\n");
      out.write("        <!-- Header -->\r\n");
      out.write("        ");

    Modelo.Usuario cliente = (Modelo.Usuario) session.getAttribute("logger");

      out.write("\r\n");
      out.write("<header class=\"superior\">\r\n");
      out.write("    <div class=\"izquierda\">\r\n");
      out.write("        <img src=\"");
      out.print( contextPath);
      out.write("/recursos/logoLargo.png\" alt=\"Logo\" class=\"logo\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <nav>\r\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath());
      out.write("/vistas/Cliente/cliente.jsp\">\r\n");
      out.write("            <span>Progreso</span>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"");
      out.print( contextPath);
      out.write("/RutinaController?accion=Read\">\r\n");
      out.write("            <span>Rutinas</span>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath());
      out.write("/EntrenadorController\">\r\n");
      out.write("            <span>Entrenadores</span>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath());
      out.write("/SuscripcionController?menu=Suscripciones&accion=listar&idCliente=");
      out.print( cliente.getIdUsuario() );
      out.write("\">\r\n");
      out.write("            <span>Suscripciones</span>\r\n");
      out.write("        </a>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <div class=\"derecha\">\r\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath());
      out.write("/CerrarSesion\">\r\n");
      out.write("            <span>Cerrar Sesion</span>\r\n");
      out.write("        </a>\r\n");
      out.write("        <img src=\"");
      out.print( contextPath);
      out.write("/recursos/cliente.jpg\" alt=\"user\" class=\"user\">\r\n");
      out.write("        <span>");
      out.print( cliente.getNomUsuario() );
      out.write(' ');
      out.print( cliente.getApeUsuario() );
      out.write(' ');
      out.write('|');
      out.write(' ');
      out.print( cliente.getRolUsuario() );
      out.write("</span>\r\n");
      out.write("    </div>\r\n");
      out.write("</header>");
      out.write("\r\n");
      out.write("        <div class=\"col-md-3 mx-auto text-center\"> \r\n");
      out.write("            <h1>Tus rutinas</h1>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-md-8 mx-auto row\">\r\n");
      out.write("            <div class=\"col-md-12 align-items-center text-center row\">\r\n");
      out.write("                <!-- filtros -->\r\n");
      out.write("                <div class=\"col-md-4 me-auto\">\r\n");
      out.write("                    <div class=\"content-card p-2 row\">\r\n");
      out.write("                        <form action=\"");
      out.print( contextPath);
      out.write("/RutinaController\">\r\n");
      out.write("                            <input type=\"hidden\" name=\"accion\" value=\"Read\">\r\n");
      out.write("                            <div class=\"col-md-12\">\r\n");
      out.write("                                <label for=\"tipoFiltro\">Buscar por:</label>\r\n");
      out.write("                                <select name=\"tipoFiltro\" id=\"tipoFiltro\" class=\"form-select\">\r\n");
      out.write("                                    <option value=\"\"></option>\r\n");
      out.write("                                    <option value=\"nomRutina\">Nombre</option>\r\n");
      out.write("                                    <option value=\"semanasRutina\">Cantidad de semanas</option>\r\n");
      out.write("                                    <option value=\"descRutina\">Descripcion</option>\r\n");
      out.write("                                    <option value=\"nivelRutina\">Nivel</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-12 mt-1\">\r\n");
      out.write("                                <div class=\"input-group\">\r\n");
      out.write("                                    <input type=\"text\" name=\"filtro\" id=\"filtro\" class=\"form-control\" placeholder=\"Buscar\">\r\n");
      out.write("                                    <button class=\"buscar input-group-text\" type=\"submit\">\r\n");
      out.write("                                        <i class=\"bi bi-search\"></i>\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-4 ms-auto\">\r\n");
      out.write("                    <button class=\"nueva btn\">\r\n");
      out.write("                        <a style=\"color: white;\" href=\"");
      out.print(contextPath);
      out.write("/vistas/Entrenador/formRutina.jsp\">+ Crear nueva rutina</a>\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            ");
 List<Modelo.Rutina> listaRutinas = (List<Modelo.Rutina>) request.getAttribute("listaRutinas");
                String alerta = (String) request.getAttribute("alerta");
                if (alerta == null || alerta.equals("")) {
                    System.out.println(alerta);
                    if (listaRutinas != null && !listaRutinas.isEmpty()) {
                        for (Modelo.Rutina rutina : listaRutinas) {
      out.write("\r\n");
      out.write("            <div class=\"rutinas\">\r\n");
      out.write("                <div class=\"rutina mt-4 row\">\r\n");
      out.write("                    <div class=\"col-md-3\">\r\n");
      out.write("                        <a style=\"color: #ff0000;\" data-bs-toggle=\"modal\" data-bs-target=\"#eliminarRutina_");
      out.print(rutina.getIdRutina());
      out.write("\"><i class=\"bi bi-trash3\"></i></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-6 d-flex\">\r\n");
      out.write("                        <div class=\"my-auto mx-auto\">\r\n");
      out.write("                            <h3>");
      out.print(rutina.getNomRutina());
      out.write("</h3>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-3 text-end\">\r\n");
      out.write("                        Fecha de creacion: ");
      out.print(rutina.getCreacionRutina());
      out.write(" </br>\r\n");
      out.write("                        Nivel de dificultad: ");
      out.print(rutina.getNivelRutina());
      out.write(" </br>\r\n");
      out.write("                        Duracion: ");
      out.print(rutina.getSemanasRutina());
      out.write(" Semana/s </br>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-md-7\">\r\n");
      out.write("                        <div class=\"content-card p-3\">\r\n");
      out.write("                            <div class=\"card-header text-center\">\r\n");
      out.write("                                <h5>Descripcion</h5>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"client-list\">\r\n");
      out.write("                                ");
      out.print(rutina.getDescRutina());
      out.write(" \r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-5\">\r\n");
      out.write("                        <form action=\"");
      out.print(contextPath);
      out.write("/Ejercicio_RutinaController\">\r\n");
      out.write("                            <input type=\"hidden\" name=\"accion\" value=\"Read\">\r\n");
      out.write("                            <input type=\"hidden\" name=\"idRutina\" value=\"");
      out.print(rutina.getIdRutina());
      out.write("\">\r\n");
      out.write("                            <div class=\"row my-auto mx-auto pt-4\">\r\n");
      out.write("                                <button class=\"editar btn col-md-4 mx-auto\">Editar rutina</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </form>\r\n");
      out.write("                        <div class=\"row my-auto mx-auto pt-1\">\r\n");
      out.write("                            <button class=\"asignar btn btn-success col-md-4 mx-auto\" data-bs-toggle=\"modal\" data-bs-target=\"#clientes\">Usar rutina</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal fade\" id=\"eliminarRutina_");
      out.print(rutina.getIdRutina());
      out.write("\" aria-labelledby=\"titulos\" aria-hidden=\"true\">\r\n");
      out.write("                <div class=\"modal-dialog modal-dialog-centered\">\r\n");
      out.write("                    <div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"modal-header\">\r\n");
      out.write("                            <h5 class=\"modal-title\" id=\"titulos\">ESTAS A PUNTO DE ELIMINAR TU RUTINA!</h5>\r\n");
      out.write("                            <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Cerrar\"></button>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"modal-body\">\r\n");
      out.write("                            <form id=\"formEliminar_");
      out.print(rutina.getIdRutina());
      out.write("\" action=\"");
      out.print(contextPath);
      out.write("/RutinaController\">\r\n");
      out.write("                                <input type=\"hidden\" name=\"idRutina\" value=\"");
      out.print(rutina.getIdRutina());
      out.write("\">\r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                    Si eliminas tu rutina, no podras recuperarla posteriormente\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"modal-footer\">\r\n");
      out.write("                            <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Cancelar</button>\r\n");
      out.write("                            <button type=\"submit\" name=\"accion\" value=\"Delete\" class=\"btn eliminar\" form=\"formEliminar_");
      out.print(rutina.getIdRutina());
      out.write("\">Eliminar</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            ");
}
            } else {
      out.write("\r\n");
      out.write("            <div><h1>Primero crea una rutina</h1></div>\r\n");
      out.write("            ");
}
            } else {
      out.write("\r\n");
      out.write("            <div class=\"contenedor-alerta\">\r\n");
      out.write("                <div class=\"tarjeta-alerta\">\r\n");
      out.write("                    ");
      out.print( alerta);
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            ");
}
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
