/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.7
 * Generated at: 2025-06-25 00:52:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.vistas.admin;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.*;
import Modelo.Usuario;

public final class ListaUsuariosAdmin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/plantillas/DashAdminController.jsp", Long.valueOf(1750812714087L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("Modelo.Usuario");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    String contextPath = request.getContextPath();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("        <title>Usuarios</title>\r\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css\" rel=\"stylesheet\"\r\n");
      out.write("              integrity=\"sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT\" crossorigin=\"anonymous\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css\">\r\n");
      out.write("        <link rel=\"Stylesheet\" href=\"");
      out.print( contextPath );
      out.write("/Estilos/contenido.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"");
      out.print( contextPath );
      out.write("/Estilos/navbarEstilo.css\">\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        ");
      out.write('\r');
      out.write('\n');

    Modelo.Usuario usuario = (Modelo.Usuario) session.getAttribute("usuario");
    if (usuario != null) {

      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("    <div class=\"left\">\r\n");
      out.write("        <div class=\"brand\">\r\n");
      out.write("            <i class=\"bi bi-shop logo\"></i>\r\n");
      out.write("            <span class=\"name\">El Vecino Amigo</span>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"right\">\r\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath());
      out.write("/CerrarSesion\">\r\n");
      out.write("            <span class=\"names\">Cerrar Sesión</span>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#\">\r\n");
      out.write("            <i class=\"bi bi-plus\"></i>\r\n");
      out.write("            <span class=\"names\">Cliente</span>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"");
      out.print( contextPath );
      out.write("/UsuarioController?menu=accion&accion=Agregar\">\r\n");
      out.write("            <i class=\"bi bi-plus\"></i>\r\n");
      out.write("            <span class=\"names\">Usuario</span>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#\">\r\n");
      out.write("            <i class=\"bi bi-plus\"></i>\r\n");
      out.write("            <span class=\"names\">Producto</span>\r\n");
      out.write("        </a>\r\n");
      out.write("        <img src=\"");
      out.print( contextPath );
      out.write("/recursos/admin.jpg\" alt=\"usuario\" class=\"user\">\r\n");
      out.write("        <span class=\"names\">");
      out.print( usuario.getNomUsuario());
      out.write(' ');
      out.write('|');
      out.write(' ');
      out.print( usuario.getRolUsuario());
      out.write("</span>\r\n");
      out.write("    </div>\r\n");
      out.write("</header>\r\n");
      out.write("<div class=\"sidebar\">\r\n");
      out.write("    <ul>\r\n");
      out.write("        <li>\r\n");
      out.write("            <a href=\"");
      out.print( contextPath );
      out.write("/UsuarioController?menu=Usuarios&accion=Listar\">\r\n");
      out.write("                <i class=\"bi bi-people\"></i>\r\n");
      out.write("                <span class=\"names\">Usuarios</span>\r\n");
      out.write("            </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li>\r\n");
      out.write("            <a href=\"#\">\r\n");
      out.write("                <i class=\"bi bi-cash-stack\"></i>\r\n");
      out.write("                <span class=\"names\">Pagos</span>\r\n");
      out.write("            </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li>\r\n");
      out.write("            <a href=\"#\">\r\n");
      out.write("                <i class=\"bi bi-coin\"></i>\r\n");
      out.write("                <span class=\"names\">Creditos</span>\r\n");
      out.write("            </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li>\r\n");
      out.write("            <a href=\"#\">\r\n");
      out.write("                <i class=\"bi bi-basket\"></i>\r\n");
      out.write("                <span class=\"names\">Productos</span>\r\n");
      out.write("            </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li>\r\n");
      out.write("            <a href=\"#\">\r\n");
      out.write("                <i class=\"bi bi-people\"></i>\r\n");
      out.write("                <span class=\"names\">clientes</span>\r\n");
      out.write("            </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li>\r\n");
      out.write("            <a href=\"#\">\r\n");
      out.write("                <i class=\"bi bi-exclamation-circle\"></i>\r\n");
      out.write("                <span class=\"names\">reportes</span>\r\n");
      out.write("            </a>\r\n");
      out.write("        </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("</div>\r\n");
}
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        <div class=\"contenido\">\r\n");
      out.write("            <h1>Lista de Usuarios</h1>\r\n");
      out.write("            <button class=\"boton-agregar\"><a class=\"nav-link active\" href=\"");
      out.print( contextPath );
      out.write("/vistas/formAgregarUsuario.jsp\">Agregar</a></button>\r\n");
      out.write("            <div class=\"tabla\">\r\n");
      out.write("                <table>\r\n");
      out.write("                    <thead>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th>ID</th>\r\n");
      out.write("                            <th>Nombre</th>\r\n");
      out.write("                            <th>Apellido</th>\r\n");
      out.write("                            <th>Email</th>\r\n");
      out.write("                            <th>Rol</th>\r\n");
      out.write("                            <th>Opciones</th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </thead>\r\n");
      out.write("                    <tbody>\r\n");
      out.write("                        ");

                            List<Modelo.Usuario> lista_usu = (List<Modelo.Usuario>) request.getAttribute("lista_usu");
                            if (lista_usu != null && !lista_usu.isEmpty()) {
                                for (Modelo.Usuario u : lista_usu) {
                        
      out.write("\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>");
      out.print( u.getIdUsuario());
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print( u.getNomUsuario());
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print( u.getApeUsuario());
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print( u.getEmaUsuario());
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print( u.getRolUsuario());
      out.write("</td>\r\n");
      out.write("                            <td><button class=\"boton boton-editar\"><a href=\"");
      out.print( contextPath );
      out.write("/UsuarioController?menu=Usuarios&accion=Editar&idUsuario=");
      out.print( u.getIdUsuario());
      out.write("\">Editar</a></button>\r\n");
      out.write("                                <button class=\"boton boton-eliminar\"><a href=\"");
      out.print( contextPath );
      out.write("/UsuarioController?menu=Usuarios&accion=Eliminar&idUsuario=");
      out.print( u.getIdUsuario());
      out.write("\">Eliminar</button></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        ");

                            }
                        } else {
                        
      out.write("\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td colspan=\"2\">No hay usuarios registrados</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        ");

                            }
                        
      out.write("\r\n");
      out.write("                    </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                ");
 Modelo.Usuario usuarioEditar = (Usuario) request.getAttribute("mostrar_usuario"); 
                String idValue = (usuarioEditar != null) ? String.valueOf(usuarioEditar.getIdUsuario()) : "";
                String nomValue = (usuarioEditar != null) ? String.valueOf(usuarioEditar.getNomUsuario()) : "";
                String apeValue = (usuarioEditar != null) ? String.valueOf(usuarioEditar.getApeUsuario()) : "";
                String emaValue = (usuarioEditar != null) ? String.valueOf(usuarioEditar.getEmaUsuario()) : "";
                String passValue = (usuarioEditar != null) ? String.valueOf(usuarioEditar.getPassUsuario()) : "";
                String rolValue = (usuarioEditar != null) ? String.valueOf(usuarioEditar.getRolUsuario()) : "";
                
      out.write("\r\n");
      out.write("                <!-- Modal -->\r\n");
      out.write("                <div class=\"modal fade\" id=\"editarUsuario\" aria-labelledby=\"editarUsuarioLabel\" aria-hidden=\"true\">\r\n");
      out.write("                    <div class=\"modal-dialog modal-dialog-centered\">\r\n");
      out.write("                        <div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"modal-header\">\r\n");
      out.write("                                <h5 class=\"modal-title\" id=\"editarUsuarioLabel\">Editar Usuario</h5>\r\n");
      out.write("                                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Cerrar\"></button>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"modal-body\">\r\n");
      out.write("                                <form id=\"edicionUsuario\" action=\"UsuarioController\">\r\n");
      out.write("                                    <input type=\"hidden\" name=\"menu\" value=\"Usuarios\">\r\n");
      out.write("                                    <input type=\"hidden\" name=\"accion\" value=\"Actualizar\">\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                        <label for=\"nomUsuario\">Numero de documento</label>\r\n");
      out.write("                                        <input name=\"idUsuario\" type=\"text\" class=\"form-control\" id=\"idUsuario\" value=\"");
      out.print(idValue);
      out.write("\" readonly>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                        <label for=\"nomUsuario\">Nombre</label>\r\n");
      out.write("                                        <input name=\"nomUsuario\" type=\"text\" class=\"form-control\" id=\"nomUsuario\" value=\"");
      out.print(nomValue);
      out.write("\" required>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                        <label for=\"apeUsuario\">Apellido</label>\r\n");
      out.write("                                        <input name=\"apeUsuario\" type=\"text\" class=\"form-control\" id=\"apeUsuario\" value=\"");
      out.print(apeValue);
      out.write("\" required>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                        <label for=\"emaUsuario\">Correo Electrónico</label>\r\n");
      out.write("                                        <input name=\"emaUsuario\" type=\"email\" class=\"form-control\" id=\"emaUsuario\" value=\"");
      out.print(emaValue);
      out.write("\" required>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                        <label for=\"passUsuario\">Contraseña</label>\r\n");
      out.write("                                        <input name=\"passUsuario\" type=\"text\" class=\"form-control\" id=\"passUsuario\" value=\"");
      out.print(passValue);
      out.write("\" required>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                        <label for=\"rolUsuario\">Rol</label>\r\n");
      out.write("                                        <select name=\"rolUsuario\" class=\"form-control\" id=\"rolUsuario\" required>\r\n");
      out.write("                                            <option value=\"");
      out.print(rolValue);
      out.write('"');
      out.write('>');
      out.print(rolValue);
      out.write("</option>\r\n");
      out.write("                                            <option value=\"Administrador\">Administrador</option>\r\n");
      out.write("                                            <option value=\"Empleado\">Empleado</option>\r\n");
      out.write("                                        </select>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </form>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"modal-footer\">\r\n");
      out.write("                                <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Cancelar</button>\r\n");
      out.write("                                <button type=\"submit\" class=\"btn btn-primary\" form=\"edicionUsuario\">Guardar cambios</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("        ");
 if (usuarioEditar != null) {
            System.out.println("el objeto no esta vacio");
      out.write("\r\n");
      out.write("        <script>\r\n");
      out.write("            document.addEventListener('DOMContentLoaded', function () {\r\n");
      out.write("                var modalElement = document.getElementById('editarUsuario');\r\n");
      out.write("                if (modalElement) {\r\n");
      out.write("                    var modal = new bootstrap.Modal(modalElement);\r\n");
      out.write("                    modal.show();\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        </script>\r\n");
      out.write("        ");
} else {
            System.out.println("el objeto esta vacio");
        
      out.write("  <script></script> ");

                }
      out.write("\r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
